// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Host.Migrations.Todo
{
    [DbContext(typeof(global:: Todo.Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Todo+RecordDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = "829af27d-9ac1-4b8c-9046-1f100a3161ff",
                            CreationDate = new DateTime(2024, 4, 20, 17, 11, 51, 258, DateTimeKind.Local).AddTicks(6484),
                            Deed = "Clean house",
                            Done = true,
                            UserName = "hubibubi@gmail.com"
                        },
                        new
                        {
                            Id = "4b693b24-7a95-4c3d-9a98-817b8686ffd5",
                            CreationDate = new DateTime(2024, 4, 20, 17, 11, 51, 258, DateTimeKind.Local).AddTicks(6518),
                            Deed = "Buy stuff",
                            Done = true,
                            UserName = "hubibubi@gmail.com"
                        },
                        new
                        {
                            Id = "60e8269e-0344-4efa-9c6a-a0da4055e1e6",
                            CreationDate = new DateTime(2024, 4, 20, 17, 11, 51, 258, DateTimeKind.Local).AddTicks(6528),
                            Deed = "Go to gym",
                            Done = false,
                            UserName = "hubibubi@gmail.com"
                        },
                        new
                        {
                            Id = "97087dfb-647c-4ae2-90ed-360514fa2674",
                            CreationDate = new DateTime(2024, 4, 20, 17, 11, 51, 258, DateTimeKind.Local).AddTicks(6537),
                            Deed = "Eat",
                            Done = false,
                            UserName = "hubibubi@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
