// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Host.Migrations.Todo
{
    [DbContext(typeof(global:: Todo.Context))]
    [Migration("20240420162109_TodosRecords")]
    partial class TodosRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Todo+RecordDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = "748f1e7d-a21d-4ad9-940e-473f4617b580",
                            Deed = "Clean house",
                            Done = true,
                            UserName = "hubibubi@gmail.com"
                        },
                        new
                        {
                            Id = "276a98c5-cc02-41d6-a8b2-48b22870ae5f",
                            Deed = "Buy stuff",
                            Done = true,
                            UserName = "hubibubi@gmail.com"
                        },
                        new
                        {
                            Id = "23550fe9-1246-4f5c-8e77-fe9b0d1d2241",
                            Deed = "Go to gym",
                            Done = false,
                            UserName = "hubibubi@gmail.com"
                        },
                        new
                        {
                            Id = "bb9126ae-03a9-43d0-b639-c60ac1fb8e95",
                            Deed = "Eat",
                            Done = false,
                            UserName = "hubibubi@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
